trigger: # will build on any PR
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'

- task: HelmInstaller@0
  inputs:
    helmVersion: '3.10.3'
    installKubectl: true

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'kubernetes'
    azureResourceGroup: 'kubernetes'
    kubernetesCluster: 'simonsCluster2'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'chart/email-capture-frontend'
    releaseName: 'ec-frontend'
