version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  hapi-template:
    build:
      target: development
    image: email-capture-frontend
    container_name: email-capture-frontend
    ports:
      - "3001:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
