apiVersion: v1
kind: Service
metadata:
  labels:
    name: ec-frontend
  name: ec-frontend
spec:
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  selector:
    app: ec-frontend
