apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.service.name | default .Chart.Name }}
  name: {{ .Values.service.name | default .Chart.Name }}
spec:
  ports:
    - protocol: {{ .Values.service.protocol | quote }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.service.name | default .Chart.Name }}
