apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name | default .Chart.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.service.name | default .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.containers.repository }}:{{ .Values.containers.tag }}
        imagePullPolicy: {{ .Values.containers.pullPolicy }}
        name: {{ .Values.containers.name }}
        ports:
        - name: {{ .Values.service.name | default .Chart.Name }}
          containerPort: {{ .Values.containers.containerPort }}
        env:
        - name: CONNECTION_STRING
          value: {{ .Values.env.connectionString }}
        - name: TOPIC_NAME
          value: {{ .Values.env.topicName }}
        - name: SUBSCRIPTION_NAME
          value: {{ .Values.env.subscriptionName }}